version: 2
updates:
  - package-ecosystem: pip
    directory: /api
    schedule:
      interval: weekly
    groups:
      python-deps:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /client
    schedule:
      interval: weekly
    groups:
      client-deps:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /docs-website
    schedule:
      interval: weekly
    groups:
      docs-deps:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"

open-pull-requests-limit: 5
